apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: aGVsbG9fZGlhbmdv  # base64 encoded value for 'hello_django'
  POSTGRES_PASSWORD: aGVsbG9fZGlhbmdv  # base64 encoded value for 'hello_django'
  POSTGRES_DB: aGVsbG9fZGlhbmdv  # base64 encoded value for 'hello_django_dev'